using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PolyBridge.Generator.Builders
{
    internal class CodeBuilder
    {
        private readonly StringBuilder _sb = new();
        private readonly HashSet<string> _namespaces = new();
        
        private const string IndentString = "    ";
        
        private int _indentLevel = 0;

        public void AddUsing(string ns) => _namespaces.Add(ns);
        public void AddUsings(IEnumerable<string> nss) { foreach(var n in nss) _namespaces.Add(n); }
        
        public IDisposable StartNameSpace(string ns) => BeginScope($"namespace {ns}");

        public IDisposable StartClass(string modifiers, string name, string inheritance = null)
        {
            var line = $"{modifiers} class {name}";
            if (!string.IsNullOrEmpty(inheritance)) line += $" : {inheritance}";
            return BeginScope(line);
        }

        public IDisposable StartInterface(string modifiers, string name)
        {
            return BeginScope($"{modifiers} interface {name}");
        }

        public IDisposable StartConstructor(string modifiers, string className, string bodyPrefix = null)
        {
            var line = $"{modifiers} {className}()";
            if (!string.IsNullOrEmpty(bodyPrefix)) line += $" : {bodyPrefix}";
            return BeginScope(line);
        }

        public IDisposable StartMethod(string modifiers, string returnType, string name, bool isAsync = false, string parameters = "")
        {
            var asyncAttr = isAsync ? "async " : "";
            return BeginScope($"{modifiers} {asyncAttr}{returnType} {name}({parameters})");
        }

        public void AppendField(string access, bool isReadonly, string type, string name)
        {
            var readOnly = isReadonly ? "readonly " : "";
            AppendLine($"{access} {readOnly}{type} {name};");
        }

        public void AppendLine(string line = "")
        {
            if (string.IsNullOrWhiteSpace(line)) _sb.AppendLine();
            else _sb.AppendLine(string.Concat(Enumerable.Repeat(IndentString, _indentLevel)) + line);
        }

        public void AppendPreprocessorIf(string condition) => _sb.AppendLine($"#if {condition}");
        public void AppendPreprocessorElif(string condition) => _sb.AppendLine($"#elif {condition}");
        public void AppendPreprocessorEndif() => _sb.AppendLine("#endif");

        public IDisposable BeginScope(string line = null)
        {
            if (line != null) AppendLine(line);
            AppendLine("{");
            _indentLevel++;
            return new ScopeExit(EndBlock);
        }

        private void EndBlock() { _indentLevel--; AppendLine("}"); }

        public string GenerateFullCode()
        {
            var final = new StringBuilder();
            final.AppendLine("// <auto-generated />");
            foreach (var ns in _namespaces.OrderBy(n => n)) final.AppendLine($"using {ns};");
            final.AppendLine();
            final.Append(_sb);
            return final.ToString();
        }

        private class ScopeExit : IDisposable {
            private readonly Action _onExit;
            public ScopeExit(Action onExit) => _onExit = onExit;
            public void Dispose() => _onExit();
        }
    }
}