using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using UnityEngine;

namespace PolyBridge.Sandbox
{
    internal static class SandboxScanner
    {
        internal static List<SandboxServiceInfo> ScanAll()
        {
            var result = new List<SandboxServiceInfo>();

            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch { continue; }

                foreach (var type in types)
                {
                    try
                    {
                        var sandboxAttr = type.GetCustomAttribute<SandboxAttribute>();
                        if (sandboxAttr == null) continue;

                        var methods = ScanMethods(type);
                        var (events, bridgeProp) = ScanEvents(type);

                        if (methods.Count > 0 || events.Count > 0)
                        {
                            result.Add(new SandboxServiceInfo(sandboxAttr.DisplayName, type, methods, events, bridgeProp));
                            Debug.Log($"[PolyBridge Sandbox] Found service: {sandboxAttr.DisplayName} ({methods.Count} methods, {events.Count} events)");
                        }
                    }
                    catch (Exception e)
                    {
                        Debug.LogError($"[PolyBridge Sandbox] Failed to scan type {type.FullName}: {e}");
                    }
                }
            }

            return result;
        }

        private static List<SandboxMethodInfo> ScanMethods(Type serviceType)
        {
            var methods = new List<SandboxMethodInfo>();

            foreach (var method in serviceType.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
            {
                var attr = method.GetCustomAttribute<SandboxMethodAttribute>();
                if (attr == null) continue;

                var label = attr.Label ?? method.Name;
                var isAsync = typeof(Task).IsAssignableFrom(method.ReturnType);
                var parameters = new List<SandboxParamInfo>();

                foreach (var p in method.GetParameters())
                {
                    if (p.ParameterType == typeof(System.Threading.CancellationToken))
                        continue;
                    parameters.Add(new SandboxParamInfo(p.Name, p.ParameterType));
                }

                methods.Add(new SandboxMethodInfo(label, method, parameters, isAsync));
            }

            return methods;
        }

        private static (List<SandboxEventInfo> events, PropertyInfo bridgeProp) ScanEvents(Type serviceType)
        {
            var events = new List<SandboxEventInfo>();

            // Find "Bridge" property on the service (generated by PolyBridge)
            var bridgeProp = serviceType.GetProperty("Bridge",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

            if (bridgeProp == null)
                return (events, null);

            var bridgeType = bridgeProp.PropertyType;

            // Scan events on the bridge type — exclude callback events (OnSuccess, OnError, etc.)
            // Event methods generated from NativeBridge have matching "On" prefix + capitalized name
            foreach (var evt in bridgeType.GetEvents(BindingFlags.Public | BindingFlags.Instance))
            {
                events.Add(new SandboxEventInfo(evt.Name, evt));
            }

            return (events, bridgeProp);
        }
    }
}
